In [1]:
import numpy as np

In [2]:
adjacency_matrix = [
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]

In [3]:
def has_multiple_edges_and_no_self_loops(matrix):
    # Check if there are no self-loops
    if not np.all(np.diag(matrix) == 0):
        return False
    
    # Check if there are multiple edges between any two nodes
    for i in range(len(matrix)):
        """
        Check if there are multiple edges between any two nodes.

        Parameters:
        matrix (list of list of int): The adjacency matrix of the graph.

        Returns:
        bool: True if there are multiple edges between any two nodes, False otherwise.
        """
        for j in range(len(matrix)):
            if matrix[i][j] > 1:
                return True
    
    return False

# Check the condition for the adjacency matrix
has_multiple_edges = has_multiple_edges_and_no_self_loops(adjacency_matrix)
has_multiple_edges

False

In [4]:
# Check if there are any self-loops
"""
Check if the graph has any self-loops.

Returns:
bool: True if the graph has self-loops, False otherwise.
"""
has_self_loops = not np.all(np.diag(adjacency_matrix) == 0)
has_self_loops

False

In [5]:
"""
Check if the graph has self-loops and print the appropriate message.

Parameters:
has_self_loops (bool): True if the graph has self-loops, False otherwise.
"""

if has_self_loops:
    print("The graph has self-loops.")
else:
    print("The graph does not have self-loops.")

The graph does not have self-loops.


In [6]:
if not has_multiple_edges_and_no_self_loops(adjacency_matrix):
    print("The graph is a simple graph.")
else:
    """
    Check if the graph has multiple edges or self-loops and print the appropriate message.

    Parameters:
    has_multiple_edges_and_no_self_loops (bool): True if the graph has multiple edges or self-loops, False otherwise.
    """
    print("The graph has multiple edges between some nodes or self-loops.")

The graph is a simple graph.


In [7]:
def is_simple_graph(matrix):
    # Check if the matrix is symmetric
    """
    Check if the graph is undirected by verifying the symmetry of the adjacency matrix.

    Parameters:
    matrix (list of list of int): The adjacency matrix of the graph.

    Returns:
    bool: True if the graph is undirected, False otherwise.
    """
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] != matrix[j][i]:
                return False
    
    # Check if the diagonal elements are zero
    """
    Check if the graph has no self-loops.

    Parameters:
    matrix (list of list of int): The adjacency matrix of the graph.

    Returns:
    bool: True if the graph has no self-loops, False otherwise.
    """
    for i in range(len(matrix)):
        if matrix[i][i] != 0:
            return False
    
    return True

# Check if the adjacency matrix represents a simple graph
is_simple = is_simple_graph(adjacency_matrix)
is_simple

True

In [8]:
is_undirected = is_simple_graph(adjacency_matrix)
is_undirected

True

In [9]:
#2.  Can the adjacency matrix potentially represent an undirected graph?
# Yes, the adjacency matrix can potentially represent an undirected graph. If the matrix is symmetric and has zeros on the diagonal, it can represent an undirected graph. This is because in an undirected graph, the edge between nodes i and j is the same as the edge between nodes j and i, and there are no self-loops.
import numpy as np

def check_symmetry_and_diagonal(matrix):
    """
    Check if the adjacency matrix is symmetric and has zeros on the diagonal.

    Parameters:
    matrix (numpy.ndarray): The adjacency matrix of the graph.

    Returns:
    tuple: A tuple containing two boolean values:
        - is_symmetric (bool): True if the matrix is symmetric, False otherwise.
        - has_zero_diagonal (bool): True if the matrix has zeros on the diagonal, False otherwise.
    
    Raises:
    ValueError: If the adjacency matrix is not square.
    """
    # Check if the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("The adjacency matrix must be square.")
    
    is_symmetric = np.all(matrix == matrix.T)
    has_zero_diagonal = np.all(np.diag(matrix) == 0)
    return is_symmetric, has_zero_diagonal

# Example adjacency matrix (square matrix)
adjacency_matrix = np.array(adjacency_matrix)

# Check the symmetry and diagonal elements of the adjacency matrix
is_symmetric, has_zero_diagonal = check_symmetry_and_diagonal(adjacency_matrix)
print(f"Is symmetric: {is_symmetric}")
print(f"Has zero diagonal: {has_zero_diagonal}")


Is symmetric: True
Has zero diagonal: True


In [10]:
def check_symmetry_and_diagonal(matrix):
    is_symmetric = np.all(matrix == matrix.T)
    """
    Check if the adjacency matrix has zeros on the diagonal.

    Parameters:
    matrix (numpy.ndarray): The adjacency matrix of the graph.

    Returns:
    bool: True if the matrix has zeros on the diagonal, False otherwise.
    """
    has_zero_diagonal = np.all(np.diag(matrix) == 0)
    return is_symmetric, has_zero_diagonal

# Check the symmetry and diagonal elements of the adjacency matrix
is_symmetric, has_zero_diagonal = check_symmetry_and_diagonal(adjacency_matrix)
print(f"Is symmetric: {is_symmetric}")
print(f"Has zero diagonal: {has_zero_diagonal}")

Is symmetric: True
Has zero diagonal: True


In [11]:
#Check if the graph is connected

In [12]:
def is_connected(matrix):
    """
    Check if the graph is connected using Depth-First Search (DFS).

    Parameters:
    matrix (list of list of int): The adjacency matrix of the graph.

    Returns:
    bool: True if the graph is connected, False otherwise.
    """
    visited = [False] * len(matrix)
    
    def dfs(node):
        visited[node] = True
        for neighbor, is_connected in enumerate(matrix[node]):
            if is_connected and not visited[neighbor]:
                dfs(neighbor)
    
    # Start DFS from the first node
    """
    Perform DFS starting from the first node (node 0).

    Parameters:
    node (int): The starting node for DFS.
    """
    dfs(0)
    
    # Check if all nodes are visited
    """
    Check if all nodes have been visited after performing DFS.

    Returns:
    bool: True if all nodes are visited, False otherwise.
    """
    return all(visited)

# Check if the graph is connected
"""
Check if the graph is connected.

Returns:
bool: True if the graph is connected, False otherwise.
"""
is_graph_connected = is_connected(adjacency_matrix)
is_graph_connected

True

In [13]:
def find_min_l(matrix):
    """
    Find the minimum l such that all entries in the l-th power of the adjacency matrix are non-zero.

    Parameters:
    matrix (numpy.ndarray): The adjacency matrix of the graph.

    Returns:
    int: The minimum l for which all entries in the l-th power of the adjacency matrix are non-zero.
    """
    l = 1
    current_matrix = np.linalg.matrix_power(matrix, l)
    
    while np.any(current_matrix == 0):
        l += 1
        current_matrix = np.linalg.matrix_power(matrix, l)
    
    return l

# Find the minimum l for the adjacency matrix
"""
Find the minimum l for which all entries in the l-th power of the adjacency matrix are non-zero.

Returns:
int: The minimum l for which all entries in the l-th power of the adjacency matrix are non-zero.
"""
min_l = find_min_l(adjacency_matrix)
min_l

4

In [14]:
def count_connected_components(matrix):
    """
    Count the number of connected components in the graph using Depth-First Search (DFS).

    Parameters:
    matrix (list of list of int): The adjacency matrix of the graph.

    Returns:
    int: The number of connected components in the graph.
    """
    visited = [False] * len(matrix)
    count = 0
    
    def dfs(node):
        """
        Perform DFS starting from the given node.

        Parameters:
        node (int): The starting node for DFS.
        """
        visited[node] = True
        for neighbor, is_connected in enumerate(matrix[node]):
            if is_connected and not visited[neighbor]:
                dfs(neighbor)
    
    for node in range(len(matrix)):
        """
        Check each node to see if it has been visited. If not, perform DFS and increment the count of connected components.

        Parameters:
        node (int): The current node being checked.
        """
        if  not visited[node]:
           dfs(node)
        count += 1
    
    return count

# Count the number of connected components in the adjacency matrix
"""
Count the number of connected components in the adjacency matrix.

Returns:
int: The number of connected components in the graph.
"""
num_connected_components = count_connected_components(adjacency_matrix)
num_connected_components

10

In [15]:
def max_degree(matrix):
    degrees = np.sum(matrix, axis=1)
    """
    Calculate the maximum degree of a node in the graph.

    Parameters:
    matrix (list of list of int): The adjacency matrix of the graph.

    Returns:
    int: The maximum degree of a node in the graph.
    """
    return np.max(degrees)

# Find the maximum degree of a node in the adjacency matrix
max_node_degree = max_degree(adjacency_matrix)
max_node_degree

np.int64(5)

In [16]:
# Compute the 5th power of the adjacency matrix
adjacency_matrix_power_5 = np.linalg.matrix_power(adjacency_matrix, 5)
"""
Compute the 5th power of the adjacency matrix.

Parameters:
matrix (numpy.ndarray): The adjacency matrix of the graph.

Returns:
numpy.ndarray: The 5th power of the adjacency matrix.
"""

# Number of walks of length 5 from node 0 to itself
walks_length_5 = adjacency_matrix_power_5[0, 0]
"""
Compute the number of walks of length 5 from node 0 to itself.

Parameters:
adjacency_matrix_power_5 (numpy.ndarray): The 5th power of the adjacency matrix.

Returns:
int: The number of walks of length 5 from node 0 to itself.
"""
walks_length_5

np.int64(46)

In [17]:
import numpy as np
#calculate adjacency matrix squared
adjacency_matrix_squared = np.linalg.matrix_power(adjacency_matrix, 2)

In [18]:
print(adjacency_matrix_squared)

[[3 1 1 2 1 1 0 1 1 0]
 [1 4 0 1 0 2 0 1 2 1]
 [1 0 1 1 1 0 0 0 0 0]
 [2 1 1 5 2 1 0 0 0 1]
 [1 0 1 2 3 0 1 0 1 1]
 [1 2 0 1 0 2 0 1 1 0]
 [0 0 0 0 1 0 1 0 1 0]
 [1 1 0 0 0 1 0 1 1 0]
 [1 2 0 0 1 1 1 1 3 1]
 [0 1 0 1 1 0 0 0 1 3]]


In [19]:
np.trace(adjacency_matrix_squared)

np.int64(26)

In [24]:
#family tree
#Consider the family tree of a family of people. Assume that the edges are directed and an edge represents a biological  parent, child relationship. Also, assume that the graph has a finite number of nodes and edges (so that one or both of the parents of some nodes are not represented in this tree). 
#The adjacency matrix of this graph will be a square matrix where the rows and columns represent the individuals in the family tree. The value of the element at row i and column j will be 1 if there is a biological relationship from individual i to individual j, and 0 otherwise. The adjacency matrix will be a binary matrix with 1s representing the presence of an edge and 0s representing the absence of an edge.
family_tree_adjacency_matrix = [[0, 1, 1, 0, 0, 0],
 [0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]                     

In [29]:
def min_in_degree(matrix):
    in_degrees = np.sum(matrix, axis=1)
    return np.min(in_degrees)

# Find the minimum in-degree of a node in the adjacency matrix
min_node_in_degree = min_in_degree(family_tree_adjacency_matrix)
min_node_in_degree

np.int64(0)

In [30]:
def max_in_degree(matrix):
    in_degrees = np.sum(matrix, axis=1)
    return np.max(in_degrees)

# Find the minimum in-degree of a node in the adjacency matrix
min_node_in_degree = max_in_degree(family_tree_adjacency_matrix)
min_node_in_degree

np.int64(2)

In [31]:
# Check if there are any self-loops
"""
Check if the graph has any self-loops.

Returns:
bool: True if the graph has self-loops, False otherwise.
"""
has_self_loops = not np.all(np.diag(family_tree_adjacency_matrix) == 0)
has_self_loops

False

In [32]:
"""
Check if the graph has self-loops and print the appropriate message.

Parameters:
has_self_loops (bool): True if the graph has self-loops, False otherwise.
"""

if has_self_loops:
    print("The graph has self-loops.")
else:
    print("The graph does not have self-loops.")

The graph does not have self-loops.


In [34]:
#read text file
from fileinput import filename
import pandas as pd
import numpy as np
file = pd.read_csv('release_directed_graph.txt', sep=" ", header=None)

In [35]:
file.head()

0   1
0  0   3
1  0  10
2  0  12
3  0  25
4  0  39

In [ ]:
# Determine the number of nodes
num_nodes = file.max().max() + 1

# Initialize the adjacency matrix with zeros
adj_matrix_file = np.zeros((num_nodes, num_nodes), dtype=int)

# Populate the adjacency matrix based on the file data
for _, row in file.iterrows():
    adj_matrix_file[row[0], row[1]] = 1

# Display the adjacency matrix
adj_matrix_file

In [ ]:
#convert file in to adjacency matrix by considering nodes in file[0] and edges in file[1]

In [ ]:
#Consider The file is in the edge list format with each line “i j" indicating a directed edge from vertex i to vertex j.


In [46]:
file[0].nunique()

100

In [40]:
num_edges = len(file)
num_edges

1030

In [41]:
print(f"The graph has {num_nodes} nodes.")

The graph has 1030 nodes.


In [42]:
# Check if the graph contains self-loops based on the file data
has_self_loops_file = any(file[0] == file[1])
has_self_loops_file

True

In [45]:
from collections import defaultdict, deque

def has_directed_cycles(matrix):
    """
    Check if the graph has directed cycles not involving self-loops using Kahn's algorithm for topological sorting.

    Parameters:
    matrix (numpy.ndarray): The adjacency matrix of the graph.

    Returns:
    bool: True if the graph has directed cycles not involving self-loops, False otherwise.
    """
    num_nodes = matrix.shape[0]
    in_degree = np.sum(matrix, axis=0)
    
    # Initialize a queue with nodes having zero in-degree
    queue = deque([node for node in range(num_nodes) if in_degree[node] == 0])
    
    count_visited = 0
    
    while queue:
        node = queue.popleft()
        count_visited += 1
        
        for neighbor in range(num_nodes):
            if matrix[node][neighbor] == 1:
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)
    
    # If count_visited is not equal to num_nodes, there is a cycle
    return count_visited != num_nodes

# Convert the file data to an adjacency matrix
num_nodes = file.max().max() + 1
adj_matrix_file = np.zeros((num_nodes, num_nodes), dtype=int)
for _, row in file.iterrows():
    adj_matrix_file[row[0], row[1]] = 1

# Check for directed cycles not involving self-loops
has_cycles = has_directed_cycles(adj_matrix_file)
has_cycles

True